steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ci-perl540'
    args: ['build', '-t', 'gcr.io/perl-cloud-ci/google-cloud-perl-ci-540:latest', '-f', 'ci/Dockerfile.perl540', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ci-debian'
    waitFor: ['-']
    args: ['build', '-t', 'gcr.io/perl-cloud-ci/google-cloud-perl-ci-debian:latest', '-f', 'ci/Dockerfile.debian', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ci-ubuntu'
    waitFor: ['-']
    args: ['build', '-t', 'gcr.io/perl-cloud-ci/google-cloud-perl-ci-ubuntu:latest', '-f', 'ci/Dockerfile.ubuntu', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ci-rocky'
    waitFor: ['-']
    args: ['build', '-t', 'gcr.io/perl-cloud-ci/google-cloud-perl-ci-rocky:latest', '-f', 'ci/Dockerfile.rocky', '.']

images:
  - 'gcr.io/perl-cloud-ci/google-cloud-perl-ci-540:latest'
  - 'gcr.io/perl-cloud-ci/google-cloud-perl-ci-debian:latest'
  - 'gcr.io/perl-cloud-ci/google-cloud-perl-ci-ubuntu:latest'
  - 'gcr.io/perl-cloud-ci/google-cloud-perl-ci-rocky:latest'

timeout: '1800s'
options:
  machineType: 'N1_HIGHCPU_8'
