FROM docker.io/rockylinux:9

RUN dnf install -y dnf-plugins-core epel-release && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9 2>/dev/null || true && \
    dnf config-manager --set-enabled crb || true && \
    dnf install --enablerepo=epel,crb -y \
    perl perl-core perl-App-cpanminus perl-local-lib perl-Template-Toolkit perl-LWP-Protocol-https perl-IO-Socket-SSL \
    perl-Path-Tiny perl-Log-Any perl-Capture-Tiny perl-URI perl-File-Which \
    perl-JSON-XS perl-JSON-MaybeXS perl-Moo perl-Type-Tiny perl-Test-Exception perl-Test-Deep perl-Test-MockModule \
    gcc gcc-c++ make openssl-devel libnghttp2-devel pcre2-devel pkgconfig which protobuf-compiler && \
    cpanm Protocol::HTTP2 Module::Starter Test::LWP::UserAgent LWP::UserAgent Perl::Tidy Perl::Critic Test::Perl::Critic Test::CPAN::Changes Test::Kwalitee Test::PerlTidy Perl::Critic::Community Perl::Critic::Policy::RegularExpressions::RequireDefault Perl::Critic::Policy::Security::RandBytesFromHash && \
    ln -sf /usr/local/bin/cpanm /usr/bin/cpanm 2>/dev/null || true && \
    rm -rf ~/.cpanm && dnf clean all
