# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install Chocolatey Package Manager
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

# Install Strawberry Perl 5.42, protoc, and OpenSSL
RUN choco install strawberryperl --version=5.42.2.1 --no-progress -y
RUN choco install protoc openssl git --no-progress -y

# Set Environment Variables for Perl & System Tools
ENV PATH="C:\ProgramData\chocolatey\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Strawberry\c\bin;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0"
ENV PACKAGE_STASH_IMPLEMENTATION="PP"
ENV MOO_XS_DISABLE="1"
ENV TEMPLATE_STASH="Template::Stash"

# Pre-install all required Perl CPAN module dependencies using perl executable explicitly
RUN cpanm Log::Any Const::Fast Sub::Identify SUPER Guard Env::Sanctify Test::Valgrind Template Moo Package::Stash Type::Tiny Protocol::HTTP2 JSON::MaybeXS Path::Tiny Capture::Tiny Module::Starter File::Which Test::Warnings Test::Exception Test::LWP::UserAgent Test::Differences Test::Needs Test::Fatal Test::Pod Test::Pod::Coverage URI HTTP::Message LWP::Protocol::https Mozilla::CA HTTP::Daemon IO::Socket::SSL Perl::Tidy PPI Perl::Critic Test::Perl::Critic Test::CPAN::Changes Test::Kwalitee Test::PerlTidy Perl::Critic::Community Perl::Critic::Policy::RegularExpressions::RequireDefault Perl::Critic::Policy::Security::RandBytesFromHash

WORKDIR C:/workspace

CMD ["powershell"]
