FROM docker.io/library/perl:5.40

RUN apt-get update && apt-get install -y \
    perl-modules cpanminus liblocal-lib-perl libtemplate-perl \
    gcc g++ make libssl-dev libcrypt-dev libnghttp2-dev libpcre2-dev libabsl-dev pkg-config protobuf-compiler && \
    cpanm Moo Type::Tiny Protocol::HTTP2 JSON::MaybeXS JSON::XS Template Path::Tiny Log::Any Capture::Tiny URI File::Which Module::Starter LWP::Protocol::https Test::More Test::Pod Test::Pod::Coverage Test::Exception Test::Deep Test::MockModule Test::LWP::UserAgent Perl::Tidy Perl::Critic Test::Perl::Critic Test::CPAN::Changes Test::Kwalitee Test::PerlTidy Perl::Critic::Community Perl::Critic::Policy::RegularExpressions::RequireDefault Perl::Critic::Policy::Security::RandBytesFromHash && \
    rm -rf ~/.cpanm /var/lib/apt/lists/*
